export const jobs =[
    {
        "id" : "1",
        "title" : "Cyber Security Engineer",
        "location" : "Dallas",
        "short_description" : "gdsajhb",
        "long_description" : "ahgsdhgjas",
        "benefits" : "dasmhsavhjbsa",
        "company" : "sdbn dblqwe ewjq,",
        "num_veterans_hired" : "4",
        "date" : "",
        "experience" : "",
    },
    {
        "id" : "2",
        "title" : "Cyber Security Engineer A",
        "location" : "Dallas",
        "short_description" : "gdsajhb",
        "long_description" : "ahgsdhgjas",
        "benefits" : "dasmhsavhjbsa",
        "company" : "sdbn dblqwe ewjq,",
        "num_veterans_hired" : "4",
        "date" : "",
        "experience" : "",
    },
    {
        "id" : "3",
        "title" : "Cyber Security Engineer B",
        "location" : "Dallas",
        "short_description" : "gdsajhb",
        "long_description" : "ahgsdhgjas",
        "benefits" : "dasmhsavhjbsa",
        "company" : "sdbn dblqwe ewjq,",
        "num_veterans_hired" : "4",
        "date" : "",
        "experience" : "",
    },
    {
        "id" : "4",
        "title" : "Cyber Security AEngineer C",
        "location" : "Dallas",
        "short_description" : "gdsajhb",
        "long_description" : "ahgsdhgjas",
        "benefits" : "dasmhsavhjbsa",
        "company" : "sdbn dblqwe ewjq,",
        "num_veterans_hired" : "4",
        "date" : "",
        "experience" : "",
    }

];